require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  TargetRubyVersion: 2.7
  DisplayCopNames: true
  DisplayStyleGuide: true
  NewCops: enable
  Exclude:
    - db/schema.rb

Metrics/BlockLength:
  Exclude:
    - "spec/**/*.rb"

Metrics/AbcSize:
  Max: 20

Layout/LineLength:
  Max: 120

Metrics/ClassLength:
  Max: 200

Metrics/MethodLength:
  Max: 20

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/Documentation:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/SpaceInLambdaLiteral:
  EnforcedStyle: require_space

Layout/SpaceInsideStringInterpolation:
  EnforcedStyle: space

Naming/MemoizedInstanceVariableName:
  EnforcedStyleForLeadingUnderscores: required

Layout/HashAlignment:
  EnforcedHashRocketStyle: key
  EnforcedColonStyle: key

Lint/AmbiguousBlockAssociation:
  Exclude:
    - "spec/**/*"

RSpec/EmptyExampleGroup:
  Enabled: false

RSpec/ExampleLength:
  Max: 10

RSpec/HookArgument:
  Enabled: false

RSpec/ImplicitBlockExpectation:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Max: 10

RSpec/ContextWording:
  Prefixes:
    - when
    - with
    - without
    - and
    - but
    - for

Style/ExpandPathArguments:
  Exclude:
    - bin/rails
    - bin/rake
    
Rails/BulkChangeTable:
  Enabled: false

Rails/HttpPositionalArguments:
  Enabled: false

Rails/NotNullColumn:
  Enabled: false

Rails/FilePath:
  EnforcedStyle: arguments

Rails/UnknownEnv:
  Environments:
    - development
    - production
    - test
