AllCops:
  TargetRubyVersion: 2.7
  DisplayCopNames: true
  DisplayStyleGuide: true
  NewCops: enable
  Exclude:
    - db/schema.rb

Metrics/BlockLength:
  Exclude:
    - "spec/**/*.rb"

Metrics/AbcSize:
  Max: 20

Layout/LineLength:
  Max: 120

Metrics/ClassLength:
  Max: 200

Metrics/MethodLength:
  Max: 20

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/Documentation:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/SpaceInLambdaLiteral:
  EnforcedStyle: require_space

Layout/SpaceInsideStringInterpolation:
  EnforcedStyle: space

Naming/MemoizedInstanceVariableName:
  EnforcedStyleForLeadingUnderscores: required

Layout/HashAlignment:
  EnforcedHashRocketStyle: key
  EnforcedColonStyle: key

Lint/AmbiguousBlockAssociation:
  Exclude:
    - "spec/**/*"
